# Generated by Django 3.0 on 2020-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ave_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_Time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time_to_complete', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
